"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { useAuth } from "@/contexts/AuthContext";
import { deliveryNotesRepo, trucksRepo, tripsRepo } from "@/lib/firebase/modules";
import type { BaseRecord, DeliveryNote, Trip, Truck, TruckStatus } from "@/types/core";

const STATUS_STYLE: Record<TruckStatus, string> = { available: "green", on_trip: "blue", in_maintenance: "yellow", out_of_service: "red" };
const tripLabel = (status: Trip["status"]) => ({ completed: "Completed", exception: "Alert", in_transit: "In progress", en_route_pickup: "En route", loading: "Loading", unloading: "Unloading", planned: "Scheduled" }[status] ?? status);
const dateText = (value: Trip["plannedStart"]) => value.toDate().toLocaleDateString("en-BW", { day: "2-digit", month: "short", year: "numeric" });

export default function TrucksPage() {
  const router = useRouter(); const { activeOrg } = useWorkspace(); const { user } = useAuth();
  const [trucks,setTrucks]=useState<Truck[]|null>(null); const [trips,setTrips]=useState<Trip[]>([]); const [deliveryNotes,setDeliveryNotes]=useState<DeliveryNote[]>([]);
  const [error,setError]=useState<string|null>(null); const [showCreate,setShowCreate]=useState(false); const [editTruck,setEditTruck]=useState<Truck|null>(null); const [selectedTruckId,setSelectedTruckId]=useState("all"); const [selectedDate,setSelectedDate]=useState("");
  useEffect(()=>{if(!activeOrg)return;const id=activeOrg.id;const a=trucksRepo.subscribe(id,{environment:"LIVE",orderByField:"registrationNumber"},setTrucks,e=>setError(e.message));const b=tripsRepo.subscribe(id,{environment:"LIVE"},setTrips,e=>setError(e.message));const c=deliveryNotesRepo.subscribe(id,{environment:"LIVE"},setDeliveryNotes,e=>setError(e.message));return()=>{a();b();c()}},[activeOrg]);
  const visibleTrips=useMemo(()=>trips.filter(t=>(selectedTruckId==="all"||t.truckId===selectedTruckId)&&(!selectedDate||t.plannedStart.toDate().toISOString().slice(0,10)===selectedDate)),[trips,selectedTruckId,selectedDate]);
  const activeTrips=trips.filter(t=>t.status!=="completed"); const exceptions=trips.filter(t=>t.status==="exception"); const podComplete=deliveryNotes.filter(n=>n.podState==="complete").length;
  const archiveTruck=async(truck:Truck)=>{if(!activeOrg||!user)return;if(!confirm(`Retire ${truck.registrationNumber} from the active fleet?`))return;try{const token=await user.getIdToken();const r=await fetch("/api/operations/archive-record",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({orgId:activeOrg.id,entity:"truck",id:truck.id})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Truck could not be retired.");setError(null)}catch(e){setError(e instanceof Error?e.message:"Truck could not be retired.")}};
  if(!activeOrg)return null;
  return <div className="space-y-6">
    <header className="page-header"><div><h1 className="page-title">Fleet &amp; Live Map</h1><p className="page-subtitle">Truck Division · Live movement, route progress, service alerts and trip history</p></div><div className="flex items-center gap-2"><span className="badge green">LIVE DATA</span><button onClick={()=>setShowCreate(true)} className="btn-primary">+ New truck</button></div></header>
    {error&&<div className="notice" style={{borderColor:"#F3C3C3",background:"var(--red-100)",color:"#902323"}}>{error}</div>}
    <section className="panel"><div className="section-header"><div><h2 className="section-title">Fleet Register</h2><p className="section-sub">Edit live vehicle records or safely retire vehicles from the active register.</p></div><span className="badge blue">{trucks?.length??0} active records</span></div>{trucks?.length?<div className="list">{trucks.map(truck=>{const busy=trips.some(t=>t.truckId===truck.id&&t.status!=="completed");return <div className="list-row" key={truck.id}><div style={{minWidth:0}}><div className="flex items-center gap-2 flex-wrap"><strong>{truck.registrationNumber}</strong><span className={`badge ${STATUS_STYLE[truck.status]}`}>{truck.status.replaceAll("_"," ")}</span>{busy&&<span className="badge yellow">Active trip</span>}</div><div className="muted">{truck.make||"Unknown make"} {truck.model||""} · {truck.capacityTons||0}t · VIN {truck.vinNumber||"not recorded"}</div></div><div className="flex gap-2 flex-wrap"><button className="btn-secondary" type="button" onClick={()=>setEditTruck(truck)}>Edit</button><button className="btn-ghost" type="button" disabled={busy} title={busy?"Complete or reassign the active trip before retiring this truck.":"Retire this truck"} onClick={()=>archiveTruck(truck)}>Retire</button></div></div>})}</div>:<DatabaseNotice title="No trucks registered" body="Create the first vehicle to start the live fleet register."/>}</section>
    <section className="kpi-grid"><Metric label="Active Trucks" value={trucks?.filter(t=>t.status==="on_trip").length||0} note={`${trucks?.filter(t=>t.status==="available").length||0} available`} tone="teal"/><Metric label="PODs Captured" value={`${podComplete}/${deliveryNotes.length}`} note={`${Math.max(deliveryNotes.length-podComplete,0)} awaiting completion`} tone="green"/><Metric label="Route Alerts" value={exceptions.length} note={exceptions.length?"Trip exceptions requiring review":"No live trip exceptions"} tone={exceptions.length?"red":"green"}/></section>
    <section className="panel" style={{padding:0,overflow:"hidden"}}><div className="section-header" style={{padding:"20px 22px 14px",marginBottom:0}}><div><h2 className="section-title">Live Fleet Map</h2><p className="section-sub">Live operational position from the current trip/location fields.</p></div><span className="badge green">Live operational feed</span></div><div style={{position:"relative",minHeight:280,background:"linear-gradient(135deg,var(--teal-50),var(--cream),var(--surface-3))",borderTop:"1px solid var(--divider)"}}><div style={{position:"absolute",inset:0,opacity:.55,backgroundImage:"linear-gradient(rgba(12,108,125,.10) 1px,transparent 1px),linear-gradient(90deg,rgba(12,108,125,.10) 1px,transparent 1px)",backgroundSize:"42px 42px"}}/>{(trucks||[]).slice(0,6).map((truck,i)=>{const trip=activeTrips.find(t=>t.truckId===truck.id);const left=[10,28,46,63,77,86][i]||50;const top=[58,30,70,43,23,67][i]||50;return <div key={truck.id} style={{position:"absolute",left:`${left}%`,top:`${top}%`,transform:"translate(-50%,-50%)",minWidth:150}}><div className="panel" style={{padding:12,boxShadow:"var(--shadow-md)"}}><div className="flex justify-between gap-2 items-center"><strong style={{fontSize:12}}>{truck.registrationNumber}</strong><span className={`badge ${STATUS_STYLE[truck.status]}`}>{truck.status.replaceAll("_"," ")}</span></div><div className="muted" style={{fontSize:10.5,marginTop:7}}>{trip?.currentLocation||(trip?"Trip in progress":"No active trip")}</div>{trip&&<div style={{color:"var(--teal)",fontSize:10.5,fontWeight:700,marginTop:5}}>{tripLabel(trip.status)}</div>}</div></div>})}</div></section>
    <section className="panel"><div className="section-header"><div><h2 className="section-title">Trip Lookup</h2><p className="section-sub">Pick a truck and date to see live trip logs.</p></div><div className="flex gap-2"><select className="form-input" value={selectedTruckId} onChange={e=>setSelectedTruckId(e.target.value)}><option value="all">All trucks</option>{trucks?.map(t=><option key={t.id} value={t.id}>{t.registrationNumber}</option>)}</select><input className="form-input" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></div></div>{visibleTrips.length?<div className="list">{visibleTrips.slice(0,12).map(t=><div className="list-row" key={t.id}><div><strong>{t.jobNumber||t.id.slice(0,10)}</strong><div className="muted">{t.truckRegistration} · {t.currentLocation||"Location not recorded"} · planned {dateText(t.plannedStart)}</div></div><div className="flex gap-2 flex-wrap"><span className={`badge ${t.status==="exception"?"red":t.status==="completed"?"green":"blue"}`}>{tripLabel(t.status)}</span><button className="btn-ghost" type="button" onClick={()=>router.push(`/trips?tripId=${encodeURIComponent(t.id)}`)}>Open Trip Sheet</button></div></div>)}</div>:<DatabaseNotice title="No matching trip records" body="Try another truck/date, or add trips through the Trips workflow."/>}</section>
    {showCreate&&<TruckFormDialog orgId={activeOrg.id} onClose={()=>setShowCreate(false)} onCreated={()=>setShowCreate(false)}/>} {editTruck&&<TruckEditDialog orgId={activeOrg.id} truck={editTruck} onClose={()=>setEditTruck(null)}/>} 
  </div>;
}
function Metric({label,value,note,tone}:{label:string;value:number|string;note:string;tone:"teal"|"green"|"blue"|"orange"|"red"}){return <div className={`kpi-card ${tone}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-sub">{note}</div></div>}
function DatabaseNotice({title,body}:{title:string;body:string}){return <div className="notice blue" style={{marginTop:12}}><strong>{title}</strong><div style={{marginTop:4}}>{body}</div></div>}
function TruckFormDialog({orgId,onClose,onCreated}:{orgId:string;onClose:()=>void;onCreated:()=>void}){const{user}=useAuth();const[f,setF]=useState({registrationNumber:"",make:"",model:"",year:new Date().getFullYear(),vinNumber:"",capacityTons:0});const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const submit=async(e:FormEvent)=>{e.preventDefault();if(!user)return;setBusy(true);try{const p:Omit<Truck,keyof BaseRecord>={registrationNumber:f.registrationNumber.trim().toUpperCase(),make:f.make.trim(),model:f.model.trim(),year:Number(f.year),vinNumber:f.vinNumber.trim(),capacityTons:Number(f.capacityTons),fuelType:"diesel",status:"available",odometerKm:0,assignedDriverId:null,complianceExpiryDates:{licenseDisc:null,roadworthy:null,insurance:null},notes:""};if(!p.registrationNumber)throw new Error("Registration number is required.");await trucksRepo.create(orgId,user.uid,p,"LIVE");onCreated()}catch(e){setError(e instanceof Error?e.message:"Truck could not be created.")}finally{setBusy(false)}};return <Dialog title="New truck" onClose={onClose}><form onSubmit={submit}><TruckFields form={f} setForm={setF}/>{error&&<div className="notice">{error}</div>}<Actions onClose={onClose} busy={busy} label="Create truck"/></form></Dialog>}
function TruckEditDialog({orgId,truck,onClose}:{orgId:string;truck:Truck;onClose:()=>void}){const{user}=useAuth();const[f,setF]=useState({registrationNumber:truck.registrationNumber,make:truck.make||"",model:truck.model||"",year:truck.year||new Date().getFullYear(),vinNumber:truck.vinNumber||"",capacityTons:truck.capacityTons||0});const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const submit=async(e:FormEvent)=>{e.preventDefault();if(!user)return;setBusy(true);try{await trucksRepo.update(orgId,user.uid,truck.id,{registrationNumber:f.registrationNumber.trim().toUpperCase(),make:f.make.trim(),model:f.model.trim(),year:Number(f.year),vinNumber:f.vinNumber.trim(),capacityTons:Number(f.capacityTons)});onClose()}catch(e){setError(e instanceof Error?e.message:"Truck could not be updated.")}finally{setBusy(false)}};return <Dialog title="Edit truck" onClose={onClose}><form onSubmit={submit}><TruckFields form={f} setForm={setF}/>{error&&<div className="notice">{error}</div>}<Actions onClose={onClose} busy={busy} label="Save changes"/></form></Dialog>}
function TruckFields({form,setForm}:{form:{registrationNumber:string;make:string;model:string;year:number;vinNumber:string;capacityTons:number};setForm:React.Dispatch<React.SetStateAction<any>>}){return <><Field label="Registration number"><input className="form-input" value={form.registrationNumber} onChange={e=>setForm((x:any)=>({...x,registrationNumber:e.target.value}))}/></Field><div className="form-grid"><Field label="Make"><input className="form-input" value={form.make} onChange={e=>setForm((x:any)=>({...x,make:e.target.value}))}/></Field><Field label="Model"><input className="form-input" value={form.model} onChange={e=>setForm((x:any)=>({...x,model:e.target.value}))}/></Field></div><div className="form-grid"><Field label="Year"><input className="form-input" type="number" value={form.year} onChange={e=>setForm((x:any)=>({...x,year:Number(e.target.value)}))}/></Field><Field label="Capacity (tons)"><input className="form-input" type="number" value={form.capacityTons} onChange={e=>setForm((x:any)=>({...x,capacityTons:Number(e.target.value)}))}/></Field></div><Field label="VIN number"><input className="form-input" value={form.vinNumber} onChange={e=>setForm((x:any)=>({...x,vinNumber:e.target.value}))}/></Field></>}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-20 flex items-center justify-center bg-black/60 px-4"><div className="form-card" style={{width:"100%",maxWidth:560}}><div className="section-header"><h2 className="section-title">{title}</h2><button type="button" onClick={onClose} className="btn-ghost">✕</button></div>{children}</div></div>}
function Actions({onClose,busy,label}:{onClose:()=>void;busy:boolean;label:string}){return <div className="form-actions" style={{justifyContent:"flex-end"}}><button type="button" onClick={onClose} className="btn-ghost">Cancel</button><button type="submit" disabled={busy} className="btn-primary">{busy?"Saving…":label}</button></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="form-group"><span className="field-label">{label}</span>{children}</label>}
