"use client";
import { useEffect, useMemo, useState } from "react";
import { Timestamp } from "firebase/firestore";
import { useAuth } from "@/contexts/AuthContext";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { invoicesRepo, invoicePaymentsRepo, supplierBillsRepo, chartAccountsRepo, accountingPeriodsRepo } from "@/lib/firebase/modules";
import type { Invoice } from "@/types/finance";
import type { InvoicePayment, SupplierBill, ChartAccount, AccountingPeriod } from "@/types/business";

export default function BusinessControlsPage(){
 const {activeOrg}=useWorkspace(); const {user}=useAuth();
 const [invoices,setInvoices]=useState<Invoice[]>([]),[payments,setPayments]=useState<InvoicePayment[]>([]),[bills,setBills]=useState<SupplierBill[]>([]),[accounts,setAccounts]=useState<ChartAccount[]>([]),[periods,setPeriods]=useState<AccountingPeriod[]>([]);
 const [message,setMessage]=useState<string|null>(null);
 const [payment,setPayment]=useState({invoiceId:"",amount:"",reference:"",method:"bank_transfer"});
 const [bill,setBill]=useState({supplier:"",reference:"",amount:"",due:""});
 const [account,setAccount]=useState({code:"",name:"",category:"expense"});
 const [period,setPeriod]=useState({name:"",start:"",end:""});
 useEffect(()=>{if(!activeOrg)return; const id=activeOrg.id, q={environment:"LIVE" as const}; return ()=>{};},[activeOrg]);
 useEffect(()=>{if(!activeOrg)return;const id=activeOrg.id,q={environment:"LIVE" as const};const u=[invoicesRepo.subscribe(id,q,setInvoices),invoicePaymentsRepo.subscribe(id,q,setPayments),supplierBillsRepo.subscribe(id,q,setBills),chartAccountsRepo.subscribe(id,q,setAccounts),accountingPeriodsRepo.subscribe(id,q,setPeriods)];return()=>u.forEach(x=>x());},[activeOrg]);
 if(!activeOrg||!user)return null;
 const received=payments.reduce((s,p)=>s+p.amount,0), outstanding=invoices.filter(i=>i.status!=="paid"&&i.status!=="void").reduce((s,i)=>s+i.amount,0), now=Date.now(), overdue=invoices.filter(i=>i.status==="issued"&&i.dueAt&&i.dueAt.toMillis()<now).length;
 const pay=async()=>{const i=invoices.find(x=>x.id===payment.invoiceId);if(!i||!payment.amount)return setMessage("Select an invoice and amount.");const amount=Number(payment.amount);try{await invoicePaymentsRepo.create(activeOrg.id,user.uid,{invoiceId:i.id,invoiceNumber:i.invoiceNumber,customerId:i.customerId,customerName:i.customerName,amount,currency:i.currency,paidAt:Timestamp.now(),reference:payment.reference||`PAY-${Date.now().toString(36).toUpperCase()}`,method:payment.method as InvoicePayment["method"]},"LIVE");const total=payments.filter(p=>p.invoiceId===i.id).reduce((s,p)=>s+p.amount,0)+amount;if(total>=i.amount)await invoicesRepo.update(activeOrg.id,user.uid,i.id,{status:"paid",paidAt:Timestamp.now()});setPayment({invoiceId:"",amount:"",reference:"",method:"bank_transfer"});setMessage("Payment recorded against the invoice.");}catch(e){setMessage(e instanceof Error?e.message:"Payment failed.");}};
 const saveBill=async()=>{if(!bill.supplier||!bill.amount)return setMessage("Supplier and amount are required.");await supplierBillsRepo.create(activeOrg.id,user.uid,{supplierPOId:null,supplier:bill.supplier,reference:bill.reference||`BILL-${Date.now().toString(36).toUpperCase()}`,amount:Number(bill.amount),currency:activeOrg.currency,dueAt:bill.due?Timestamp.fromDate(new Date(bill.due+"T00:00:00")):null,status:"open",paidAt:null},"LIVE");setBill({supplier:"",reference:"",amount:"",due:""});setMessage("Supplier bill recorded.");};
 const saveAccount=async()=>{if(!account.code||!account.name)return setMessage("Account code and name are required.");await chartAccountsRepo.create(activeOrg.id,user.uid,{...account,category:account.category as ChartAccount["category"],active:true},"LIVE");setAccount({code:"",name:"",category:"expense"});setMessage("Chart account added.");};
 const savePeriod=async()=>{if(!period.name||!period.start||!period.end)return setMessage("Period name, start and end are required.");await accountingPeriodsRepo.create(activeOrg.id,user.uid,{name:period.name,startsAt:Timestamp.fromDate(new Date(period.start+"T00:00:00")),endsAt:Timestamp.fromDate(new Date(period.end+"T23:59:59")),status:"open"},"LIVE");setPeriod({name:"",start:"",end:""});setMessage("Accounting period opened.");};
 const markBillPaid=async(b:SupplierBill)=>{await supplierBillsRepo.update(activeOrg.id,user.uid,b.id,{status:"paid",paidAt:Timestamp.now()});setMessage("Supplier bill marked paid.");};
 return <div className="space-y-6"><header className="page-header"><div><h1 className="page-title">Business Controls</h1><p className="page-subtitle">Receivables, payables and accounting control from persisted workspace records.</p></div><span className="badge green">LIVE DATA</span></header>{message&&<div className="notice blue">{message}</div>}
 <div className="kpi-grid"><K label="Outstanding invoices" v={String(invoices.filter(i=>i.status==="issued").length)} n={`${activeOrg.currency} ${outstanding.toLocaleString()} open`}/><K label="Overdue" v={String(overdue)} n="Issued past due date" t="orange"/><K label="Payments received" v={`${activeOrg.currency} ${received.toLocaleString()}`} n="Recorded payments" t="green"/><K label="Supplier bills" v={String(bills.filter(b=>b.status==="open").length)} n="Open payables" t="blue"/></div>
 <section className="grid-2 section"><div className="form-card"><h3>Record customer payment</h3><Form label="Invoice" value={payment.invoiceId} set={v=>setPayment({...payment,invoiceId:v})} options={invoices.filter(i=>i.status==="issued").map(i=>({v:i.id,l:`${i.invoiceNumber} · ${i.customerName} · ${i.amount}`}))}/><Form label="Amount" value={payment.amount} set={v=>setPayment({...payment,amount:v})} type="number"/><Form label="Reference" value={payment.reference} set={v=>setPayment({...payment,reference:v})}/><Form label="Method" value={payment.method} set={v=>setPayment({...payment,method:v})} options={["bank_transfer","cash","mobile_money","other"].map(v=>({v,l:v.replaceAll("_"," ")}))}/><button className="btn-primary" onClick={pay}>Record payment</button></div><div className="form-card"><h3>Customer statement register</h3><Table h={["Customer","Invoice","Amount","Status","Due"]} r={invoices.slice(0,12).map(i=>[i.customerName,i.invoiceNumber,`${i.currency} ${i.amount}`,i.status,i.dueAt?.toDate().toLocaleDateString()??"—"])}/></div></section>
 <section className="grid-2 section"><div className="form-card"><h3>Record supplier bill</h3><Form label="Supplier" value={bill.supplier} set={v=>setBill({...bill,supplier:v})}/><Form label="Reference" value={bill.reference} set={v=>setBill({...bill,reference:v})}/><Form label="Amount" value={bill.amount} set={v=>setBill({...bill,amount:v})} type="number"/><Form label="Due date" value={bill.due} set={v=>setBill({...bill,due:v})} type="date"/><button className="btn-primary" onClick={saveBill}>Record supplier bill</button></div><div className="form-card"><h3>Payables register</h3>{bills.slice(0,12).map(b=><div className="list-row" key={b.id}><div><strong>{b.supplier}</strong><div className="muted">{b.reference} · {b.currency} {b.amount.toLocaleString()}</div></div>{b.status==="open"?<button className="btn-secondary" onClick={()=>markBillPaid(b)}>Mark paid</button>:<span className="badge green">PAID</span>}</div>)}</div></section>
 <section className="grid-2 section"><div className="form-card"><h3>Chart of accounts</h3><Form label="Code" value={account.code} set={v=>setAccount({...account,code:v})}/><Form label="Name" value={account.name} set={v=>setAccount({...account,name:v})}/><Form label="Category" value={account.category} set={v=>setAccount({...account,category:v})} options={["asset","liability","equity","revenue","expense"].map(v=>({v,l:v}))}/><button className="btn-primary" onClick={saveAccount}>Add account</button><div className="panel-sub">{accounts.length} persisted accounts.</div></div><div className="form-card"><h3>Accounting periods</h3><Form label="Name" value={period.name} set={v=>setPeriod({...period,name:v})}/><Form label="Start" value={period.start} set={v=>setPeriod({...period,start:v})} type="date"/><Form label="End" value={period.end} set={v=>setPeriod({...period,end:v})} type="date"/><button className="btn-primary" onClick={savePeriod}>Open period</button><div className="panel-sub">{periods.length} persisted periods.</div></div></section>
 </div>;
}
function K({label,v,n,t=""}:{label:string;v:string;n:string;t?:string}){return <div className={`kpi-card ${t}`}><div className="kpi-label">{label}</div><div className="kpi-value">{v}</div><div className="kpi-sub">{n}</div></div>}
function Form({label,value,set,type="text",options}:{label:string;value:string;set:(v:string)=>void;type?:string;options?:{v:string;l:string}[]}){return <label className="form-group"><span className="field-label">{label}</span>{options?<select className="form-select" value={value} onChange={e=>set(e.target.value)}><option value="">Select…</option>{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select>:<input className="form-input" type={type} value={value} onChange={e=>set(e.target.value)}/>}</label>}
function Table({h,r}:{h:string[];r:string[][]}){return <div style={{overflowX:"auto"}}><table className="data-table"><thead><tr>{h.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{r.map((x,i)=><tr key={i}>{x.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}