"use client";

import { useEffect, useState } from "react";
import { Timestamp } from "firebase/firestore";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { useAuth } from "@/contexts/AuthContext";
import { maintenanceSchedulesRepo, tyreRecordsRepo, vehicleInspectionsRepo, trucksRepo, workOrdersRepo } from "@/lib/firebase/modules";
import type { Truck } from "@/types/core";
import type { WorkOrder } from "@/types/finance";
import type { MaintenanceSchedule, TyreRecord, VehicleInspection } from "@/types/workshop";

export default function WorkshopControl() {
  const { activeOrg } = useWorkspace(); const { user } = useAuth();
  const [trucks, setTrucks] = useState<Truck[]>([]); const [orders, setOrders] = useState<WorkOrder[]>([]); const [schedules, setSchedules] = useState<MaintenanceSchedule[]>([]); const [inspections, setInspections] = useState<VehicleInspection[]>([]); const [tyres, setTyres] = useState<TyreRecord[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [schedule, setSchedule] = useState({ truckId: "", serviceType: "Routine service", intervalKm: "", intervalDays: "", nextDueKm: "", notes: "" });
  const [inspection, setInspection] = useState({ truckId: "", type: "pre_trip", result: "pass", odometerKm: "", findings: "", inspectorName: "", nextDue: "" });
  const [tyre, setTyre] = useState({ truckId: "", position: "", serial: "", brand: "", size: "", odometer: "", notes: "" });

  useEffect(() => { if (!activeOrg) return; const id = activeOrg.id; const unsubs = [
    trucksRepo.subscribe(id, { environment: "LIVE", orderByField: "registrationNumber" }, setTrucks),
    workOrdersRepo.subscribe(id, { environment: "LIVE", orderByField: "createdAt", orderDirection: "desc" }, setOrders),
    maintenanceSchedulesRepo.subscribe(id, { environment: "LIVE" }, setSchedules),
    vehicleInspectionsRepo.subscribe(id, { environment: "LIVE", orderByField: "inspectionDate", orderDirection: "desc" }, setInspections),
    tyreRecordsRepo.subscribe(id, { environment: "LIVE" }, setTyres),
  ]; return () => unsubs.forEach(u => u()); }, [activeOrg]);
  if (!activeOrg) return null;

  const truck = (id: string) => trucks.find(t => t.id === id);
  const saveSchedule = async () => { if (!user) return; const t = truck(schedule.truckId); if (!t || !schedule.serviceType.trim()) { setMessage("Select a truck and service type."); return; } try { await maintenanceSchedulesRepo.create(activeOrg.id, user.uid, { truckId: t.id, truckRegistration: t.registrationNumber, serviceType: schedule.serviceType.trim(), intervalKm: Number(schedule.intervalKm) || null, intervalDays: Number(schedule.intervalDays) || null, nextDueKm: Number(schedule.nextDueKm) || null, nextDueAt: null, lastCompletedKm: null, lastCompletedAt: null, status: "active", notes: schedule.notes.trim() }, "LIVE"); setMessage("Maintenance schedule saved."); setSchedule({ ...schedule, serviceType: "Routine service", intervalKm: "", intervalDays: "", nextDueKm: "", notes: "" }); } catch (e) { setMessage(e instanceof Error ? e.message : "Failed to save schedule."); } };
  const saveInspection = async () => { if (!user) return; const t = truck(inspection.truckId); if (!t || !inspection.inspectorName.trim()) { setMessage("Truck and inspector are required."); return; } try { await vehicleInspectionsRepo.create(activeOrg.id, user.uid, { truckId: t.id, truckRegistration: t.registrationNumber, inspectionDate: Timestamp.now(), inspectionType: inspection.type as VehicleInspection["inspectionType"], result: inspection.result as VehicleInspection["result"], odometerKm: Number(inspection.odometerKm) || t.odometerKm, findings: inspection.findings.trim(), inspectorName: inspection.inspectorName.trim(), nextDueAt: inspection.nextDue ? Timestamp.fromDate(new Date(`${inspection.nextDue}T00:00:00`)) : null }, "LIVE"); setMessage("Inspection record saved."); setInspection({ ...inspection, odometerKm: "", findings: "", inspectorName: "", nextDue: "" }); } catch (e) { setMessage(e instanceof Error ? e.message : "Failed to save inspection."); } };
  const saveTyre = async () => { if (!user) return; const t = truck(tyre.truckId); if (!t || !tyre.position.trim() || !tyre.serial.trim()) { setMessage("Truck, position and serial number are required."); return; } try { await tyreRecordsRepo.create(activeOrg.id, user.uid, { truckId: t.id, truckRegistration: t.registrationNumber, position: tyre.position.trim(), serialNumber: tyre.serial.trim(), brand: tyre.brand.trim(), size: tyre.size.trim(), fittedAt: Timestamp.now(), fittedOdometerKm: Number(tyre.odometer) || t.odometerKm, currentOdometerKm: Number(tyre.odometer) || t.odometerKm, status: "fitted", notes: tyre.notes.trim() }, "LIVE"); setMessage("Tyre record saved."); setTyre({ ...tyre, position: "", serial: "", brand: "", size: "", odometer: "", notes: "" }); } catch (e) { setMessage(e instanceof Error ? e.message : "Failed to save tyre record."); } };
  const advanceOrder = async (order: WorkOrder) => { if (!user) return; const flow: WorkOrder["status"][] = ["open", "approved", "completed"]; const next = flow[Math.max(0, flow.indexOf(order.status)) + 1]; if (!next) return; await workOrdersRepo.update(activeOrg.id, user.uid, order.id, { status: next }); setMessage(`${order.workOrderNumber} moved to ${next}.`); };

  return <div className="space-y-6">
    <header className="page-header"><div><h1 className="page-title">Workshop Control</h1><p className="page-subtitle">Maintenance lifecycle, service schedules, inspections and tyre history for the live fleet.</p></div><span className="badge green">LIVE DATA</span></header>
    {message && <div className="notice blue">{message}</div>}
    <div className="kpi-grid"><Kpi label="Open work orders" value={String(orders.filter(o => o.status === "open").length)} note="Needs workshop action" tone="yellow" /><Kpi label="Scheduled work" value={String(orders.filter(o => o.status === "approved").length)} note="Approved queue" tone="blue" /><Kpi label="Maintenance plans" value={String(schedules.filter(s => s.status === "active").length)} note="Active schedules" /><Kpi label="Inspections" value={String(inspections.length)} note="Persisted records" tone="green" /><Kpi label="Tyres tracked" value={String(tyres.length)} note="Persisted positions" /></div>
    <section className="panel"><div className="section-header"><div><h2 className="section-title">Work-order lifecycle</h2><p className="section-sub">Open → approved → completed. Existing soft-delete/security boundaries remain intact.</p></div></div>{orders.length ? <div className="list">{orders.slice(0, 20).map(o => <div className="list-row" key={o.id}><div><strong>{o.workOrderNumber} · {o.truckRegistration}</strong><div className="muted">{o.workType} · {o.workRequired}</div></div><div className="flex gap-2"><span className={`badge ${o.status === "completed" ? "green" : o.status === "approved" ? "blue" : "yellow"}`}>{o.status}</span>{o.status !== "completed" && <button className="btn-ghost" onClick={() => void advanceOrder(o)}>Advance →</button>}</div></div>)}</div> : <div className="notice blue">No work orders yet. Create one from Fuel & Workshop.</div>}</section>
    <div className="grid grid-cols-1 gap-[14px] lg:grid-cols-3">
      <Form title="Maintenance schedule"><Field label="Truck" value={schedule.truckId} set={v => setSchedule({ ...schedule, truckId: v })} options={trucks.map(t => `${t.id}|${t.registrationNumber}`)} /><Field label="Service type" value={schedule.serviceType} set={v => setSchedule({ ...schedule, serviceType: v })} /><Field label="Interval KM" value={schedule.intervalKm} set={v => setSchedule({ ...schedule, intervalKm: v })} /><Field label="Interval days" value={schedule.intervalDays} set={v => setSchedule({ ...schedule, intervalDays: v })} /><Field label="Next due KM" value={schedule.nextDueKm} set={v => setSchedule({ ...schedule, nextDueKm: v })} /><Field label="Notes" value={schedule.notes} set={v => setSchedule({ ...schedule, notes: v })} /><button className="btn-primary" onClick={saveSchedule}>Save schedule</button></Form>
      <Form title="Vehicle inspection"><Field label="Truck" value={inspection.truckId} set={v => setInspection({ ...inspection, truckId: v })} options={trucks.map(t => `${t.id}|${t.registrationNumber}`)} /><Field label="Type" value={inspection.type} set={v => setInspection({ ...inspection, type: v })} options={["pre_trip","periodic","roadworthy","post_repair"]} /><Field label="Result" value={inspection.result} set={v => setInspection({ ...inspection, result: v })} options={["pass","attention","fail"]} /><Field label="Odometer KM" value={inspection.odometerKm} set={v => setInspection({ ...inspection, odometerKm: v })} /><Field label="Inspector" value={inspection.inspectorName} set={v => setInspection({ ...inspection, inspectorName: v })} /><Field label="Findings" value={inspection.findings} set={v => setInspection({ ...inspection, findings: v })} /><Field label="Next due" value={inspection.nextDue} set={v => setInspection({ ...inspection, nextDue: v })} type="date" /><button className="btn-primary" onClick={saveInspection}>Save inspection</button></Form>
      <Form title="Tyre tracking"><Field label="Truck" value={tyre.truckId} set={v => setTyre({ ...tyre, truckId: v })} options={trucks.map(t => `${t.id}|${t.registrationNumber}`)} /><Field label="Position" value={tyre.position} set={v => setTyre({ ...tyre, position: v })} /><Field label="Serial number" value={tyre.serial} set={v => setTyre({ ...tyre, serial: v })} /><Field label="Brand" value={tyre.brand} set={v => setTyre({ ...tyre, brand: v })} /><Field label="Size" value={tyre.size} set={v => setTyre({ ...tyre, size: v })} /><Field label="Fitted odometer" value={tyre.odometer} set={v => setTyre({ ...tyre, odometer: v })} /><Field label="Notes" value={tyre.notes} set={v => setTyre({ ...tyre, notes: v })} /><button className="btn-primary" onClick={saveTyre}>Save tyre record</button></Form>
    </div>
    <section className="panel"><h2 className="section-title">Maintenance register</h2><div className="list" style={{ marginTop: 12 }}>{schedules.slice(0, 15).map(s => <div className="list-row" key={s.id}><div><strong>{s.truckRegistration} · {s.serviceType}</strong><div className="muted">{s.nextDueKm ? `Next due at ${s.nextDueKm.toLocaleString()} km` : "Time-based due date not configured"}</div></div><span className="badge green">{s.status}</span></div>)}</div></section>
    <section className="panel"><h2 className="section-title">Inspection & tyre history</h2><div className="grid grid-cols-1 gap-[14px] lg:grid-cols-2"><div className="list">{inspections.slice(0, 10).map(i => <div className="list-row" key={i.id}><div><strong>{i.truckRegistration} · {i.inspectionType}</strong><div className="muted">{i.result} · {i.findings || "No findings recorded"}</div></div><span className="badge">{i.odometerKm.toLocaleString()} km</span></div>)}</div><div className="list">{tyres.slice(0, 10).map(t => <div className="list-row" key={t.id}><div><strong>{t.truckRegistration} · {t.position}</strong><div className="muted">{t.brand} {t.size} · {t.serialNumber}</div></div><span className="badge">{t.currentOdometerKm.toLocaleString()} km</span></div>)}</div></div></section>
  </div>;
}

function Form({ title, children }: { title: string; children: React.ReactNode }) { return <div className="form-card"><h3>{title}</h3><div className="form-grid" style={{ marginTop: 12 }}>{children}</div></div>; }
function Field({ label, value, set, options, type = "text" }: { label: string; value: string; set: (v: string) => void; options?: string[]; type?: string }) { return <label className="form-group"><span className="field-label">{label}</span>{options ? <select className="form-select" value={value} onChange={e => set(e.target.value)}><option value="">Select…</option>{options.map(o => { const [v, text] = o.split("|"); return <option key={v} value={v}>{text || v}</option>; })}</select> : <input className="form-input" type={type} value={value} onChange={e => set(e.target.value)} />}</label>; }
function Kpi({ label, value, note, tone = "" }: { label: string; value: string; note: string; tone?: string }) { return <div className={`kpi-card ${tone}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-sub">{note}</div></div>; }
