import Link from "next/link";
import styles from "./pipeline.module.css";
import PipelineUpdates from "./pipeline-updates";

type Item={stage:"PLANNED"|"BUILDING"|"RELEASED";area:string;title:string;description:string;detail:string};
const items:Item[]=[
{stage:"BUILDING",area:"Commercial flow",title:"Delivery → invoice → payment → records",description:"Finish the handoff from a completed delivery into billing, payment tracking and the financial record that follows.",detail:"Current next build area."},
{stage:"BUILDING",area:"Reliability",title:"Check the whole workflow",description:"Make sure changes made to customers, trucks, drivers, trips, deliveries and billing stay accurate and connected.",detail:"Current product-wide check."},
{stage:"BUILDING",area:"Owner QA",title:"Polish the everyday experience",description:"Keep improving mobile visibility, clear wording, readable statuses, buttons, delivery notes and recovery when something goes wrong.",detail:"Based on the owner's current QA."},
{stage:"PLANNED",area:"Admin control",title:"Manage the pipeline",description:"Allow authorised Admin users to add, edit and move pipeline items, with a clear record of what changed and when.",detail:"Future control layer."},
{stage:"PLANNED",area:"Oversight",title:"See how Translend is doing",description:"Give Admin a simple view of important activity, issues and product signals without replacing the company's day-to-day workspace.",detail:"Future oversight layer."},
{stage:"RELEASED",area:"Company workspace",title:"Real company workspace",description:"The owner works inside the company's workspace rather than a demo, with people and operational records connected to the business.",detail:"Available now."},
{stage:"RELEASED",area:"Fleet & people",title:"Customers, trucks and drivers",description:"Create and manage customers, trucks and drivers, link drivers to trucks and prepare work for the road.",detail:"Available now."},
{stage:"RELEASED",area:"Trip operations",title:"Trips and driver work",description:"Drivers can see their work, update trip progress, handle movement and unloading, and record what happened on delivery.",detail:"Available now."},
{stage:"RELEASED",area:"Delivery records",title:"Delivery notes and proof of delivery",description:"Capture delivery details and proof, then bring completed work back to the owner for follow-through.",detail:"Available now."},
{stage:"RELEASED",area:"Owner follow-through",title:"POD queue and invoicing",description:"The owner can review completed delivery paperwork and move into the invoicing side of the business.",detail:"Available now; commercial chain continues above."}];
const order=["BUILDING","PLANNED","RELEASED"] as const;
export default function PipelinePage(){const counts={planned:items.filter(i=>i.stage==="PLANNED").length,building:items.filter(i=>i.stage==="BUILDING").length,released:items.filter(i=>i.stage==="RELEASED").length};return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><div className={styles.brand}><span className={styles.mark}>T</span><div><strong>Translend</strong><span>TMS · Truck Division</span></div></div><nav className={styles.nav} aria-label="Pipeline navigation"><Link href="/translend">Operations</Link><span className={styles.active}>Pipeline</span></nav></header><section className={styles.hero}><span className={styles.eyebrow}>Translend pipeline</span><h1>The Truck Division keeps moving.</h1><p>See what the app can do today, what we are tightening now, and what comes next. The owner can add dated updates and a Loom walkthrough below.</p><div className={styles.meta}><span>Owner updates are dated</span><span>Loom links welcome</span><span>Admin control later</span></div></section><section className={styles.stats}><Stat label="Planned" value={counts.planned}/><Stat label="Building" value={counts.building}/><Stat label="Released" value={counts.released}/><Stat label="Tracked" value={items.length}/></section><section className={styles.board}>{order.map(stage=><div className={styles.column} key={stage}><div className={styles.columnHeader}><div><span className={styles.stage}>{stage}</span><h2>{stage==="BUILDING"?"Working on now":stage==="PLANNED"?"What's next":"Already in the app"}</h2></div><span className={styles.count}>{items.filter(i=>i.stage===stage).length}</span></div><div className={styles.cards}>{items.filter(i=>i.stage===stage).map(item=><article className={styles.card} key={item.title}><span className={styles.area}>{item.area}</span><h3>{item.title}</h3><p>{item.description}</p><div className={styles.detail}>{item.detail}</div></article>)}</div></div>)}</section><PipelineUpdates/><footer className={styles.footer}><span>Translend TMS · Truck Division</span><span>Product pipeline · Owner updates</span></footer></div></main>}
function Stat({label,value}:{label:string;value:number}){return <div className={styles.stat}><span>{label}</span><strong>{value}</strong></div>}
