"use client";
import type { ReactNode } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { LoadingScreen,ErrorScreen } from "@/components/ui/FullScreenState";
import SignInScreen from "@/components/layout/SignInScreen";
import CompanySetupScreen from "@/components/layout/CompanySetupScreen";
import WorkspaceChooserScreen from "@/components/layout/WorkspaceChooserScreen";
export default function AppGate({children}:{children:ReactNode}){const auth=useAuth();const workspace=useWorkspace();if(auth.status==="error"&&(!auth.error?.recoverable||!auth.user))return <ErrorScreen title="We couldn't sign you in" message={auth.error?.message??"An unknown authentication error occurred."} onRetry={auth.retry}/>;if(auth.status==="unauthenticated")return <SignInScreen/>;if(auth.status==="authenticating")return <LoadingScreen title="Signing you in…" subtitle="Waiting on Google authentication."/>;if(workspace.status==="idle"||workspace.status==="checking_workspace")return <LoadingScreen title="Loading Translend…" subtitle="Checking your company workspace."/>;if(workspace.status==="error")return <ErrorScreen title="We couldn't load your workspace" message={workspace.error??"An unknown workspace error occurred."} onRetry={workspace.refresh} onSignOut={auth.signOut}/>;if(workspace.status==="company_setup")return <CompanySetupScreen/>;if(workspace.status==="application"&&!workspace.activeOrg&&workspace.organizations.length>1)return <WorkspaceChooserScreen/>;if(workspace.status==="application"&&workspace.activeOrg&&workspace.activeMembership)return <>{children}</>;return <ErrorScreen title="Workspace unavailable" message="Your workspace selection could not be resolved. Please retry." onRetry={workspace.refresh} onSignOut={auth.signOut}/>}
