"use client";
import { useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useWorkspace } from "@/contexts/WorkspaceContext";

export default function TaxVatPage() {
  const { activeOrg } = useWorkspace(); const { user } = useAuth();
  const [enabled,setEnabled]=useState(false); const [rate,setRate]=useState("0"); const [mode,setMode]=useState("exclusive"); const [code,setCode]=useState("VAT"); const [registration,setRegistration]=useState(""); const [legalName,setLegalName]=useState(""); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{ if(!activeOrg||!user)return; void (async()=>{ const token=await user.getIdToken(); const r=await fetch(`/api/accounting/tax-settings?orgId=${encodeURIComponent(activeOrg.id)}`,{headers:{Authorization:`Bearer ${token}`}}); const p=await r.json(); if(r.ok&&p.settings){setEnabled(Boolean(p.settings.enabled));setRate(String(p.settings.standardRate??0));setMode(String(p.settings.mode??"exclusive"));setCode(String(p.settings.taxCode??"VAT"));setRegistration(String(p.settings.registrationNumber??""));setLegalName(String(p.settings.legalName??""));} })(); },[activeOrg,user]);
  const save=async()=>{ if(!activeOrg||!user)return; setBusy(true);setMessage(null);try{const token=await user.getIdToken();const r=await fetch("/api/accounting/tax-settings",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({orgId:activeOrg.id,enabled,standardRate:Number(rate),mode,taxCode:code,registrationNumber:registration,legalName})});const p=await r.json();if(!r.ok)throw new Error(String(p.error??"Could not save tax configuration."));setMessage(p.message);}catch(e){setMessage(e instanceof Error?e.message:"Could not save tax configuration.");}finally{setBusy(false);}};
  return <div className="space-y-6"><header className="page-header"><div><h1 className="page-title">Tax & VAT</h1><p className="page-subtitle">Workspace-level tax configuration for authoritative billing and document calculations.</p></div><span className="badge green">LIVE CONTROL</span></header>{message&&<div className="notice blue">{message}</div>}<div className="notice blue">Configuration is restricted to Owner and Finance. The rate and mode are stored with the workspace and are intended to drive future invoice tax calculation; no tax is hard-coded into documents.</div><section className="form-card"><h3>VAT configuration</h3><div className="form-grid"><label className="form-group"><span className="field-label">VAT enabled</span><select className="form-select" value={enabled?"yes":"no"} onChange={e=>setEnabled(e.target.value==="yes")}><option value="no">No / exempt</option><option value="yes">Yes</option></select></label><label className="form-group"><span className="field-label">Standard rate (%)</span><input className="form-input" type="number" min="0" max="100" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label className="form-group"><span className="field-label">Calculation mode</span><select className="form-select" value={mode} onChange={e=>setMode(e.target.value)}><option value="exclusive">Tax added to net price</option><option value="inclusive">Tax included in entered price</option></select></label><label className="form-group"><span className="field-label">Tax code</span><input className="form-input" value={code} onChange={e=>setCode(e.target.value)}/></label><label className="form-group"><span className="field-label">VAT registration number</span><input className="form-input" value={registration} onChange={e=>setRegistration(e.target.value)}/></label><label className="form-group"><span className="field-label">Legal tax name</span><input className="form-input" value={legalName} onChange={e=>setLegalName(e.target.value)}/></label></div><div className="form-row-actions"><button className="btn-primary" type="button" disabled={busy} onClick={save}>{busy?"Saving…":"Save tax configuration"}</button></div></section></div>;
}
