import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { translendFirestore } from '@/lib/translend/firebase/client'
export type BusinessCollection = 'trucks'|'drivers'|'jobs'|'dispatches'|'trips'|'routes'|'deliveries'|'pods'|'exceptions'
export type BusinessField = { key:string; label:string; required?:boolean; type?:'text'|'number'|'date'|'select'; options?:string[] }
export type BusinessRecord = Record<string,string|number|null> & { id:string; createdAt?:unknown; updatedAt?:unknown; createdBy?:string }
const f=(fields:BusinessField[])=>fields
export const BUSINESS_CONFIG:Record<BusinessCollection,{title:string;description:string;fields:BusinessField[]}>= {
trucks:{title:'Trucks',description:'Company vehicles available for operational trips.',fields:f([{key:'unit',label:'Unit',required:true},{key:'registration',label:'Registration',required:true},{key:'type',label:'Type',required:true},{key:'status',label:'Status',type:'select',options:['active','maintenance','inactive']},{key:'odometer',label:'Odometer',type:'number'},{key:'nextService',label:'Next service',type:'date'},{key:'notes',label:'Notes'}])},
drivers:{title:'Drivers',description:'Drivers available for dispatch and operational assignment.',fields:f([{key:'name',label:'Name',required:true},{key:'phone',label:'Phone'},{key:'license',label:'License',required:true},{key:'licenseExpiry',label:'License expiry',type:'date'},{key:'status',label:'Status',type:'select',options:['active','off-duty','inactive']},{key:'notes',label:'Notes'}])},
jobs:{title:'Jobs',description:'Customer transport work prepared for dispatch.',fields:f([{key:'reference',label:'Reference',required:true},{key:'customerId',label:'Customer ID',required:true},{key:'routeId',label:'Route ID'},{key:'status',label:'Status',type:'select',options:['draft','planned','dispatched','in-transit','delivered','cancelled']},{key:'value',label:'Job value',type:'number'},{key:'pickupDate',label:'Pickup date',type:'date'},{key:'notes',label:'Notes'}])},
dispatches:{title:'Dispatch',description:'Planned movement assignments connecting jobs to fleet resources.',fields:f([{key:'reference',label:'Dispatch reference',required:true},{key:'jobId',label:'Job ID',required:true},{key:'truckId',label:'Truck ID',required:true},{key:'driverId',label:'Driver ID',required:true},{key:'status',label:'Status',type:'select',options:['planned','assigned','released','cancelled']},{key:'dispatchDate',label:'Dispatch date',type:'date'},{key:'notes',label:'Notes'}])},
trips:{title:'Trips',description:'Operational movement created from dispatch.',fields:f([{key:'reference',label:'Trip reference',required:true},{key:'jobId',label:'Job ID',required:true},{key:'dispatchId',label:'Dispatch ID',required:true},{key:'routeId',label:'Route ID',required:true},{key:'truckId',label:'Truck ID',required:true},{key:'driverId',label:'Driver ID',required:true},{key:'status',label:'Status',type:'select',options:['planned','loading','in-transit','arrived','completed','cancelled']},{key:'startDate',label:'Start date',type:'date'},{key:'notes',label:'Notes'}])},
routes:{title:'Routes',description:'Reusable transport routes referenced by jobs and trips.',fields:f([{key:'name',label:'Route name',required:true},{key:'origin',label:'Origin',required:true},{key:'destination',label:'Destination',required:true},{key:'distance',label:'Distance',type:'number'},{key:'status',label:'Status',type:'select',options:['active','inactive']},{key:'notes',label:'Notes'}])},
deliveries:{title:'Deliveries',description:'Trip/job completion records and delivery status.',fields:f([{key:'reference',label:'Delivery reference',required:true},{key:'tripId',label:'Trip ID',required:true},{key:'jobId',label:'Job ID',required:true},{key:'destination',label:'Destination',required:true},{key:'status',label:'Status',type:'select',options:['planned','out-for-delivery','delivered','failed']},{key:'podId',label:'POD ID'},{key:'deliveryDate',label:'Delivery date',type:'date'},{key:'notes',label:'Notes'}])},
pods:{title:'POD',description:'Proof-of-delivery records linked to completed deliveries.',fields:f([{key:'reference',label:'POD reference',required:true},{key:'deliveryId',label:'Delivery ID',required:true},{key:'tripId',label:'Trip ID',required:true},{key:'receivedBy',label:'Received by',required:true},{key:'status',label:'Status',type:'select',options:['pending','received','verified','rejected']},{key:'receivedDate',label:'Received date',type:'date'},{key:'notes',label:'Notes'}])},
exceptions:{title:'Exceptions',description:'Operational issues that require attention or resolution.',fields:f([{key:'reference',label:'Exception reference',required:true},{key:'tripId',label:'Trip ID'},{key:'deliveryId',label:'Delivery ID'},{key:'type',label:'Type',required:true},{key:'severity',label:'Severity',type:'select',options:['low','medium','high','critical']},{key:'status',label:'Status',type:'select',options:['open','investigating','resolved']},{key:'notes',label:'Notes'}])},
}
function recordsRef(org:string,name:BusinessCollection){return collection(translendFirestore,'organizations',org,name)}
export async function getBusinessRecords(org:string,name:BusinessCollection){const s=await getDocs(query(recordsRef(org,name),orderBy('createdAt','desc')));return s.docs.map(d=>({id:d.id,...d.data()})) as BusinessRecord[]}
export async function createBusinessRecord(org:string,name:BusinessCollection,userId:string,values:Record<string,string|number|null>){const now=serverTimestamp();const r=await addDoc(recordsRef(org,name),{...values,createdBy:userId,createdAt:now,updatedAt:now});return r.id}
export async function updateBusinessRecord(org:string,name:BusinessCollection,id:string,values:Record<string,string|number|null>){await updateDoc(doc(translendFirestore,'organizations',org,name,id),{...values,updatedAt:serverTimestamp()})}
export async function deleteBusinessRecord(org:string,name:BusinessCollection,id:string){await deleteDoc(doc(translendFirestore,'organizations',org,name,id))}
